// Auto-generated from default-prompts/ folder
// Do not edit this file directly - edit files in default-prompts/ instead

export const DEFAULT_FOLDERS = [
  {
    "id": "fld_business",
    "name": "Business",
    "parentId": "fld_root",
    "created": "2025-09-26T11:05:20.067Z"
  },
  {
    "id": "fld_writing",
    "name": "Writing",
    "parentId": "fld_root",
    "created": "2025-09-26T11:05:20.071Z"
  }
];

export const DEFAULT_PROMPTS = {
  "pmt_email_writer": {
    "id": "pmt_email_writer",
    "title": "Professional Email Writer",
    "body": "Write a professional email for [PURPOSE] to [RECIPIENT]. Keep it [TONE] and include [KEY POINTS].",
    "folderId": "fld_business",
    "tags": [
      "email",
      "business",
      "communication"
    ],
    "created": "2025-09-26T11:05:20.071Z",
    "lastUsed": null
  },
  "pmt_blog_helper": {
    "id": "pmt_blog_helper",
    "title": "Blog Post Helper",
    "body": "Help me write a blog post about [TOPIC]:\n\n1. Create an engaging title\n2. Write an introduction that hooks readers\n3. Outline 3-5 main points\n4. Suggest a compelling conclusion\n5. Recommend relevant tags and categories\n\nTarget audience: [AUDIENCE]\nTone: [TONE - professional/casual/technical]",
    "folderId": "fld_writing",
    "tags": [
      "writing",
      "blog",
      "content"
    ],
    "created": "2025-09-26T11:05:20.072Z",
    "lastUsed": null
  }
};
